DROP TABLE IF EXISTS idms;
CREATE TABLE idms (
   ID       INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
   IDM      CHAR(20) NOT NULL,
   NAME     CHAR(100) NOT NULL,
   CREATED  DATE NOT NULL,
   MODIFIED DATE NOT NULL
);
